name: Deploy to Azure Vm

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: |
          npm install
          npm run build
          # pm2 start
          # sleep 5 # Wait for PM2 to start up
          pm2 stop 1
          pm2 start 1
          pm2 save
          echo 12345678 | sudo -S sudo systemctl restart nginx
